"""Optional Internet script to download and inspect public Snort rule sources.

Run this on your machine if Internet is available:
    python scripts/fetch_real_sources.py

It downloads public/open rule archives into data/raw/extracted_sources and extracts
only small metadata/skeleton information for traceability. The final student dataset
is still generated by src/snort_rag/generate_dataset.py.
"""
from __future__ import annotations

import io
import re
import tarfile
import urllib.request
from pathlib import Path

URLS = {
    "et_open_snort_29": "https://rules.emergingthreats.net/open/snort-2.9.0/emerging.rules.tar.gz",
    "snort_community": "https://www.snort.org/downloads/community/community-rules.tar.gz",
}

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "raw" / "extracted_sources"
RULE_RE = re.compile(r"^(alert|drop|reject|pass|log)\s+(tcp|udp|icmp|ip)\s+.*\(.*sid:\d+;.*rev:\d+;.*\)")


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    summary_lines = []
    for name, url in URLS.items():
        print(f"Downloading {name}: {url}")
        try:
            data = urllib.request.urlopen(url, timeout=60).read()
        except Exception as exc:
            summary_lines.append(f"{name}: download failed: {exc}")
            continue
        archive_path = OUT / f"{name}.tar.gz"
        archive_path.write_bytes(data)
        count = 0
        skeletons = []
        with tarfile.open(fileobj=io.BytesIO(data), mode="r:gz") as tar:
            for member in tar.getmembers():
                if not member.name.endswith(".rules"):
                    continue
                extracted = tar.extractfile(member)
                if not extracted:
                    continue
                for raw_line in extracted.read().decode("latin1", errors="ignore").splitlines():
                    line = raw_line.strip()
                    if line.startswith("#"):
                        line = line[1:].strip()
                    if RULE_RE.match(line):
                        count += 1
                        if len(skeletons) < 50:
                            # Store only a skeleton to avoid turning the public ruleset into the personal dataset.
                            sid = re.search(r"sid:(\d+);", line)
                            msg = re.search(r'msg:"([^"]+)";', line)
                            classtype = re.search(r"classtype:([^;]+);", line)
                            skeletons.append({
                                "source_archive": name,
                                "file": member.name,
                                "sid": sid.group(1) if sid else "",
                                "msg": msg.group(1) if msg else "",
                                "classtype": classtype.group(1) if classtype else "",
                            })
        (OUT / f"{name}_skeletons.json").write_text(str(skeletons), encoding="utf-8")
        summary_lines.append(f"{name}: detected {count} rule lines; stored {len(skeletons)} metadata skeletons")
    (OUT / "download_summary.txt").write_text("\n".join(summary_lines), encoding="utf-8")
    print("\n".join(summary_lines))


if __name__ == "__main__":
    main()
